version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/home/api

  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: localhost/127.0.0.1
    ports:
      - "3333:3333"

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DATABASE: "trail_app"

    ports:
      - "5432:5432"


